ignore:
  - "external_tools/kahypar/**/*"  # ignore KaHyPar
  - "tests/**/*"
  - "tools/*"
  - "mt-kahypar/definitions.h"
  - "mt-kahypar/application/kahypar.cc"
  - "mt-kahypar/application/command_line_options.h"
  - "mt-kahypar/io/partitioning_output.h"
  - "mt-kahypar/partition/context.h"
  - "mt-kahypar/partition/context_enum_classes.h"
  - "mt-kahypar/partition/metrics.h"
  - "mt-kahypar/partition/registries/register_policies.h"
  - "mt-kahypar/partition/registries/register_preprocessing_algorithms.h"
  - "mt-kahypar/partition/registries/register_coarsening_algorithms.h"
  - "mt-kahypar/partition/registries/register_initial_partitioning_algorithms.h"
  - "mt-kahypar/partition/registries/register_refinement_algorithms.h"
  - "mt-kahypar/partition/coarsening/i_coarsener.h"
  - "mt-kahypar/partition/initial_partitioning/i_initial_partitioner.h"
  - "mt-kahypar/partition/refinement/i_refiner.h"
  - "mt-kahypar/partition/refinement/do_nothing_refiner.h"
  - "mt-kahypar/utils/*"